#!/usr/bin/env python
# -*- coding: utf-8 -*-
# check_exact_labels.py

"""
This script checks the exact duplicates identified in exact.tsv against
the original FASTA file and their corresponding labels. It verifies
whether the labels for these duplicates are identical or not,
which can indicate if they are true duplicates or if they
differ due to orientation effects.
"""

import argparse
from Bio import SeqIO


def clean_id(seq_id: str) -> str:
    """
    Removes prefixes (test_, train_, val_) to match IDs from exact.tsv
    with the original FASTA file.
    """
    for prefix in ["train_", "val_", "test_"]:
        if seq_id.startswith(prefix):
            return seq_id[len(prefix):]
    return seq_id


def main():
    parser = argparse.ArgumentParser(description="Check labels for duplicates from the exact.tsv file")
    parser.add_argument("--exact", required=True, help="The exact.tsv file (generated by the pipeline)")
    parser.add_argument("--fasta", required=True, help="Original FASTA file (e.g., test.fasta)")
    parser.add_argument("--labels", required=True, help="File with numerical values/labels for sequences (e.g., test_labels.txt)")
    args = parser.parse_args()

    fasta_records = list(SeqIO.parse(args.fasta, "fasta"))
    
    with open(args.labels) as f:
        lines = [line.strip() for line in f if line.strip()]

    label_data = lines[1:]

    id_to_values = {}
    for rec, row in zip(fasta_records, label_data):
        id_to_values[rec.id] = row.split()

    print("\n<== DUPLICATE ANALYSIS ==>")
    identical_count = 0
    different_count = 0
    not_found_count = 0

    with open(args.exact) as f:
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) < 3: 
                continue
            
            id1, id2 = parts[0], parts[1]
            orig_id1 = clean_id(id1)
            orig_id2 = clean_id(id2)

            if orig_id1 in id_to_values and orig_id2 in id_to_values:
                val1 = id_to_values[orig_id1]
                val2 = id_to_values[orig_id2]
                
                is_identical = (val1 == val2)
                
                print(f"\nPair: {orig_id1}\n  vs  {orig_id2}")
                print(f"Seq1 labels: {val1}")
                print(f"Seq2 labels: {val2}")
                
                if is_identical:
                    print(">> Result: VALUES ARE IDENTICAL")
                    identical_count += 1
                else:
                    print(">> Result: VALUES ARE DIFFERENT (Likely +/- orientation effect)")
                    different_count += 1
            else:
                not_found_count += 1

    print("\n<== SUMMARY ==>")
    print(f"Pairs with identical values: {identical_count}")
    print(f"Pairs with different values: {different_count}")
    print(f"Skipped pairs (from other datasets): {not_found_count}")


if __name__ == "__main__":
    main()
