# ==========================================
# 2. Training Configuration: Codebook (cVQ-VAE) with Oracle
# ==========================================

experiment_name: "cVQVAE_with_LegNetV2_Oracle"
seed: 7898

comet:
  api_key: ""
  project_name: "kamb"
  workspace: ""

# --- MAIN MODEL (CODEBOOK / VQ-VAE) ---
model:
  name: "HydraDNA_cVQVAE"   # VQ-VAE model name
  kwargs:
    in_ch: 4
    stem_ch: 128
    gru_dim: 128
    vq_dim: 64
    num_embeddings: 512
    depth: 2

# --- FROZEN ORACLE ATTACHMENT ---
oracle:
  apply: true
  config_path: "../../config/LegNetOracle.yaml"            # Wskazujesz na config z Kroku 1
  weights_path: "train_logs/legnet_oracle/LegNetV2_Oracle_Clean_seed7898.pth" # Wskazujesz na wygenerowane wagi

# --- DANE ---
data:
  dataset_path: "../../data/deepSTARR"
  batch_size: 128
  augment: false
  target_noise:
    apply: false

# --- PARAMETRY TRENINGU CODEBOOKA ---
training:
  epochs: 100
  batch_size: 128
  lr: 1.0e-3
  weight_decay: 1.0e-4
  early_stop: 16
  log_dir: "train_logs/cvqvae"

  # Balans Lossu dla VQ-VAE
  oracle_warmup_epochs: 16       # For 16 epochs the codebook learns DNA reconstruction only
  oracle_rampup_epochs: 4        # Over the next 4 epochs, gradually enable LegNet influence
  oracle_max_weight: 0.5         # Weight for LegNet gradients
  recon_weight: 2.0
  vq_weight: 1.0
  oracle_bidirectional: false

  scheduler:
    apply: true
    type: "cosine"
    eta_min: 1.0e-6
    warmup_fraction: 0.1
    weight_decay_scheduler: true
    weight_decay_min: 1.0e-6
  