experiment_name: "Evo2_LoRA_v1"
seed: 42

comet:
  api_key: ""
  project_name: "kamb"
  workspace: ""

model:
  name: "Evo2"
  kwargs:
    model_name: "evo2_1b_base"
    freeze_backbone: false
    lora: true
    lora_r: 8
    lora_alpha: 16.0
    hidden_dim: 256
    dropout_rate: 0.2
    pool: "mean"

data:
  dataset_path: "../../data/deepSTARR"
  batch_size: 4
  augment: false
  num_workers: 0
  strand_correct: true

training:
  lr: 5.0e-5                    # lower LR for LoRA to avoid destabilising backbone
  weight_decay: 1.0e-4
  epochs: 40
  early_stop: 10
  log_dir: "train_logs"

  scheduler:
    apply: true
    type: "cosine"
    warmup_fraction: 0.15
    eta_min: 1.0e-7
