experiment_name: "LegNet_Augmented"
seed: 7898

comet:
  api_key: ""                 # Set your Comet ML API key here
  project_name: "kamb"
  workspace: ""

model:
  name: "LegNet"
  kwargs:
    seq_len: 269              # Length including max insertion padding (249 + 20)
    in_channels: 4            # One-hot encoding
    block_sizes: [256, 256, 128, 128, 64, 64, 32, 32]
    ks: 5                     # Kernel size
    resize_factor: 4          # EfficientNet-style channel expansion
    filter_per_group: 2
    se_reduction: 4           # Squeeze-and-Excitation reduction

data:
  dataset_path: "../../data/deepSTARR"
  batch_size: 128
  augment: true
  num_workers: 4
  
  evoaug:
    max_augs_per_seq: 2
    hard_aug: false
    distribution: "poisson"
    poisson_lambda: 0.5
    augmentations:
      - name: "RandomDeletion"
        kwargs: {delete_min: 0, delete_max: 20}
      - name: "RandomRC"
        kwargs: {rc_prob: 0.5}
      - name: "RandomInsertion"
        kwargs: {insert_min: 0, insert_max: 20}
      - name: "RandomTranslocation"
        kwargs: {shift_min: 0, shift_max: 20}
      - name: "RandomMutation"
        kwargs: {mut_frac: 0.05}
      - name: "NormalizeNoise" 
        kwargs: {noise_mean: 0.0, noise_std: 0.2}

  target_noise:
    apply: true
    std: 0.05

training:
  lr: 0.0005
  weight_decay: 0.0002
  epochs: 100
  early_stop: 20
  log_dir: "train_logs"
  scheduler:
    apply: true
    type: "cosine"
    warmup_fraction: 0.05
    eta_min: 1.0e-6
