experiment_name: "SENet_Cosine"
seed: 7898

comet:
  api_key: "V6s4QJ97ca130GE8M4G4MlU5D"
  project_name: "kamb"
  workspace: "kugi8412"

model:
  name: "SEResNet"
  kwargs:
    seq_len: 249
    block_num: [2, 2, 2, 2]   # Zgodnie z implementacją ResNeta
    in_channels: 4            # Kodowanie DNA One-Hot

data:
  dataset_path: "../../data/deepSTARR"
  batch_size: 128
  augment: false
  target_noise:
    apply: false
    mean: 0.0
    std: 0.05

training:
  lr: 0.002
  weight_decay: 1e-5
  epochs: 100
  early_stop: 10
  scheduler:
    apply: true
    type: "cosine"
    warmup_fraction: 0.05
    eta_min: 2.0e-6
